### PR TITLE
(#5) - Add content-length header to post request

### PR DESCRIPTION
**Pull request by neojski**
Apparently flickr started requiring it at some point.

### CODE REVIEW

**Comment by jmblog** [comment]
+1

Nice PR! But it would be simpler with using `form.submit()`.

``` javascript
  var payload = {host: api_url_parts.host, path: '/services/upload/?format=json', method: 'POST'};
  form.submit(payload, function(err, res) { self.handleResponseStream(res); });
```

**Comment by neojski** [comment]
Flickr complained about signing when I tried `submit` but maybe I missed something. I'll try that later today and report here, thanks!

**Comment by jmblog** [comment]
Hi @neojski,

If you include `headers: form.getHeaders()` in `payload`, it doesn't work well. Anyway, good luck!

**Comment by chbrown** [comment]
Flickr has been complaining about other stuff, too -- my quickfixes have drawn out a little but I think I'm making progress.

**Comment by neojski** [comment]
Hi @jmblog, it not only works (yay! I did include form.getHeaders() in payload and it indeed didn't work. I read form-data source code and found the reason) Now it not only works but is one line shorter as well.

Hopefully npm gets updated as well.

**Comment by chbrown** [comment]
Closing along with related #5.

**Pull request closed without merging**
